//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckinSuite.mpapi {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://thinkministry.com/", ConfigurationName="mpapi.apiSoap")]
    public interface apiSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/AuthenticateUser", ReplyAction="http://thinkministry.com/apiSoap/AuthenticateUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CheckinSuite.mpapi.AuthenticateUserResponse AuthenticateUser(CheckinSuite.mpapi.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/AuthenticateUser", ReplyAction="http://thinkministry.com/apiSoap/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<CheckinSuite.mpapi.AuthenticateUserResponse> AuthenticateUserAsync(CheckinSuite.mpapi.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/AuthenticateGUIDS", ReplyAction="http://thinkministry.com/apiSoap/AuthenticateGUIDSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CheckinSuite.mpapi.AuthenticateGUIDSResponse AuthenticateGUIDS(CheckinSuite.mpapi.AuthenticateGUIDSRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/AuthenticateGUIDS", ReplyAction="http://thinkministry.com/apiSoap/AuthenticateGUIDSResponse")]
        System.Threading.Tasks.Task<CheckinSuite.mpapi.AuthenticateGUIDSResponse> AuthenticateGUIDSAsync(CheckinSuite.mpapi.AuthenticateGUIDSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/AuthenticateContactGUID", ReplyAction="http://thinkministry.com/apiSoap/AuthenticateContactGUIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CheckinSuite.mpapi.AuthenticateContactGUIDResponse AuthenticateContactGUID(CheckinSuite.mpapi.AuthenticateContactGUIDRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/AuthenticateContactGUID", ReplyAction="http://thinkministry.com/apiSoap/AuthenticateContactGUIDResponse")]
        System.Threading.Tasks.Task<CheckinSuite.mpapi.AuthenticateContactGUIDResponse> AuthenticateContactGUIDAsync(CheckinSuite.mpapi.AuthenticateContactGUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/GetDomainGUID", ReplyAction="http://thinkministry.com/apiSoap/GetDomainGUIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDomainGUID(string GUID, string Password, string ServerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/GetDomainGUID", ReplyAction="http://thinkministry.com/apiSoap/GetDomainGUIDResponse")]
        System.Threading.Tasks.Task<string> GetDomainGUIDAsync(string GUID, string Password, string ServerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/GetUserInfo", ReplyAction="http://thinkministry.com/apiSoap/GetUserInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserInfo(string GUID, string Password, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/GetUserInfo", ReplyAction="http://thinkministry.com/apiSoap/GetUserInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUserInfoAsync(string GUID, string Password, int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/FindOrCreateUserAccount", ReplyAction="http://thinkministry.com/apiSoap/FindOrCreateUserAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CheckinSuite.mpapi.FindOrCreateUserAccountResponse FindOrCreateUserAccount(CheckinSuite.mpapi.FindOrCreateUserAccountRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/FindOrCreateUserAccount", ReplyAction="http://thinkministry.com/apiSoap/FindOrCreateUserAccountResponse")]
        System.Threading.Tasks.Task<CheckinSuite.mpapi.FindOrCreateUserAccountResponse> FindOrCreateUserAccountAsync(CheckinSuite.mpapi.FindOrCreateUserAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/UpdateUserAccount", ReplyAction="http://thinkministry.com/apiSoap/UpdateUserAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateUserAccount(string GUID, string Password, int UserID, string FirstName, string LastName, string MobilePhone, string EmailAddress, string NewPassword, string MiddleName, string NickName, int PrefixID, int SuffixID, System.DateTime DOB, int GenderID, int MaritalStatusID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/UpdateUserAccount", ReplyAction="http://thinkministry.com/apiSoap/UpdateUserAccountResponse")]
        System.Threading.Tasks.Task<string> UpdateUserAccountAsync(string GUID, string Password, int UserID, string FirstName, string LastName, string MobilePhone, string EmailAddress, string NewPassword, string MiddleName, string NickName, int PrefixID, int SuffixID, System.DateTime DOB, int GenderID, int MaritalStatusID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/UpdateUserPassword", ReplyAction="http://thinkministry.com/apiSoap/UpdateUserPasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateUserPassword(string GUID, string Password, int UserID, string NewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/UpdateUserPassword", ReplyAction="http://thinkministry.com/apiSoap/UpdateUserPasswordResponse")]
        System.Threading.Tasks.Task<string> UpdateUserPasswordAsync(string GUID, string Password, int UserID, string NewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/ResetPassword", ReplyAction="http://thinkministry.com/apiSoap/ResetPasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CheckinSuite.mpapi.ResetPasswordResponse ResetPassword(CheckinSuite.mpapi.ResetPasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/ResetPassword", ReplyAction="http://thinkministry.com/apiSoap/ResetPasswordResponse")]
        System.Threading.Tasks.Task<CheckinSuite.mpapi.ResetPasswordResponse> ResetPasswordAsync(CheckinSuite.mpapi.ResetPasswordRequest request);
        
        // CODEGEN: Parameter 'FileContents' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/AttachFile", ReplyAction="http://thinkministry.com/apiSoap/AttachFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CheckinSuite.mpapi.AttachFileResponse AttachFile(CheckinSuite.mpapi.AttachFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/AttachFile", ReplyAction="http://thinkministry.com/apiSoap/AttachFileResponse")]
        System.Threading.Tasks.Task<CheckinSuite.mpapi.AttachFileResponse> AttachFileAsync(CheckinSuite.mpapi.AttachFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/UpdateDefaultImage", ReplyAction="http://thinkministry.com/apiSoap/UpdateDefaultImageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateDefaultImage(string GUID, string Password, int PageID, int RecordID, string UniqueName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/UpdateDefaultImage", ReplyAction="http://thinkministry.com/apiSoap/UpdateDefaultImageResponse")]
        System.Threading.Tasks.Task<string> UpdateDefaultImageAsync(string GUID, string Password, int PageID, int RecordID, string UniqueName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/AddRecord", ReplyAction="http://thinkministry.com/apiSoap/AddRecordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddRecord(string GUID, string Password, int UserID, string TableName, string PrimaryKeyField, string RequestString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/AddRecord", ReplyAction="http://thinkministry.com/apiSoap/AddRecordResponse")]
        System.Threading.Tasks.Task<string> AddRecordAsync(string GUID, string Password, int UserID, string TableName, string PrimaryKeyField, string RequestString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/UpdateRecord", ReplyAction="http://thinkministry.com/apiSoap/UpdateRecordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateRecord(string GUID, string Password, int UserID, string TableName, string PrimaryKeyField, string RequestString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/UpdateRecord", ReplyAction="http://thinkministry.com/apiSoap/UpdateRecordResponse")]
        System.Threading.Tasks.Task<string> UpdateRecordAsync(string GUID, string Password, int UserID, string TableName, string PrimaryKeyField, string RequestString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/ExecuteStoredProcedure", ReplyAction="http://thinkministry.com/apiSoap/ExecuteStoredProcedureResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ExecuteStoredProcedure(string GUID, string Password, string StoredProcedureName, string RequestString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/ExecuteStoredProcedure", ReplyAction="http://thinkministry.com/apiSoap/ExecuteStoredProcedureResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ExecuteStoredProcedureAsync(string GUID, string Password, string StoredProcedureName, string RequestString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/GetRecurringRecords", ReplyAction="http://thinkministry.com/apiSoap/GetRecurringRecordsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetRecurringRecords(
                    string GUID, 
                    string Password, 
                    int Pattern, 
                    int Frequency, 
                    System.DateTime StartBy, 
                    System.DateTime EndBy, 
                    int EndAfter, 
                    int SpecificDay, 
                    int OrderDay, 
                    int SpecificMonth, 
                    bool Sunday, 
                    bool Monday, 
                    bool Tuesday, 
                    bool Wednesday, 
                    bool Thursday, 
                    bool Friday, 
                    bool Saturday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/GetRecurringRecords", ReplyAction="http://thinkministry.com/apiSoap/GetRecurringRecordsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetRecurringRecordsAsync(
                    string GUID, 
                    string Password, 
                    int Pattern, 
                    int Frequency, 
                    System.DateTime StartBy, 
                    System.DateTime EndBy, 
                    int EndAfter, 
                    int SpecificDay, 
                    int OrderDay, 
                    int SpecificMonth, 
                    bool Sunday, 
                    bool Monday, 
                    bool Tuesday, 
                    bool Wednesday, 
                    bool Thursday, 
                    bool Friday, 
                    bool Saturday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/GetFirstDateInSeries", ReplyAction="http://thinkministry.com/apiSoap/GetFirstDateInSeriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime GetFirstDateInSeries(
                    string GUID, 
                    string Password, 
                    int Pattern, 
                    int Frequency, 
                    System.DateTime StartBy, 
                    System.DateTime EndBy, 
                    int EndAfter, 
                    int SpecificDay, 
                    int OrderDay, 
                    int SpecificMonth, 
                    bool Sunday, 
                    bool Monday, 
                    bool Tuesday, 
                    bool Wednesday, 
                    bool Thursday, 
                    bool Friday, 
                    bool Saturday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/GetFirstDateInSeries", ReplyAction="http://thinkministry.com/apiSoap/GetFirstDateInSeriesResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetFirstDateInSeriesAsync(
                    string GUID, 
                    string Password, 
                    int Pattern, 
                    int Frequency, 
                    System.DateTime StartBy, 
                    System.DateTime EndBy, 
                    int EndAfter, 
                    int SpecificDay, 
                    int OrderDay, 
                    int SpecificMonth, 
                    bool Sunday, 
                    bool Monday, 
                    bool Tuesday, 
                    bool Wednesday, 
                    bool Thursday, 
                    bool Friday, 
                    bool Saturday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/AddRecurringRecords", ReplyAction="http://thinkministry.com/apiSoap/AddRecurringRecordsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddRecurringRecords(
                    string GUID, 
                    string Password, 
                    int UserID, 
                    string TableName, 
                    string PrimaryKeyField, 
                    string RequestString, 
                    string csvSubTabsToCopy, 
                    int CopySubTabsFromRecordID, 
                    int Pattern, 
                    int Frequency, 
                    System.DateTime StartBy, 
                    System.DateTime EndBy, 
                    int EndAfter, 
                    int SpecificDay, 
                    int OrderDay, 
                    int SpecificMonth, 
                    bool Sunday, 
                    bool Monday, 
                    bool Tuesday, 
                    bool Wednesday, 
                    bool Thursday, 
                    bool Friday, 
                    bool Saturday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/AddRecurringRecords", ReplyAction="http://thinkministry.com/apiSoap/AddRecurringRecordsResponse")]
        System.Threading.Tasks.Task<string> AddRecurringRecordsAsync(
                    string GUID, 
                    string Password, 
                    int UserID, 
                    string TableName, 
                    string PrimaryKeyField, 
                    string RequestString, 
                    string csvSubTabsToCopy, 
                    int CopySubTabsFromRecordID, 
                    int Pattern, 
                    int Frequency, 
                    System.DateTime StartBy, 
                    System.DateTime EndBy, 
                    int EndAfter, 
                    int SpecificDay, 
                    int OrderDay, 
                    int SpecificMonth, 
                    bool Sunday, 
                    bool Monday, 
                    bool Tuesday, 
                    bool Wednesday, 
                    bool Thursday, 
                    bool Friday, 
                    bool Saturday);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUser", WrapperNamespace="http://thinkministry.com/", IsWrapped=true)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=0)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=2)]
        public string ServerName;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(string UserName, string Password, string ServerName) {
            this.UserName = UserName;
            this.Password = Password;
            this.ServerName = ServerName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUserResponse", WrapperNamespace="http://thinkministry.com/", IsWrapped=true)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=0)]
        public int FirstOutParameter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=1)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=2)]
        public int ContactID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=3)]
        public int DomainID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=4)]
        public string DomainGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=5)]
        public string UserGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=6)]
        public string DisplayName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=7)]
        public string ContactEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=8)]
        public string ExternalURL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=9)]
        public bool CanImpersonate;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(int FirstOutParameter, int UserID, int ContactID, int DomainID, string DomainGUID, string UserGUID, string DisplayName, string ContactEmail, string ExternalURL, bool CanImpersonate) {
            this.FirstOutParameter = FirstOutParameter;
            this.UserID = UserID;
            this.ContactID = ContactID;
            this.DomainID = DomainID;
            this.DomainGUID = DomainGUID;
            this.UserGUID = UserGUID;
            this.DisplayName = DisplayName;
            this.ContactEmail = ContactEmail;
            this.ExternalURL = ExternalURL;
            this.CanImpersonate = CanImpersonate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateGUIDS", WrapperNamespace="http://thinkministry.com/", IsWrapped=true)]
    public partial class AuthenticateGUIDSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=0)]
        public string UserGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=1)]
        public string DomainGUID;
        
        public AuthenticateGUIDSRequest() {
        }
        
        public AuthenticateGUIDSRequest(string UserGUID, string DomainGUID) {
            this.UserGUID = UserGUID;
            this.DomainGUID = DomainGUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateGUIDSResponse", WrapperNamespace="http://thinkministry.com/", IsWrapped=true)]
    public partial class AuthenticateGUIDSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=0)]
        public int FirstOutParameter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=1)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=2)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=3)]
        public int ContactID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=4)]
        public int DomainID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=5)]
        public string DisplayName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=6)]
        public string ContactEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=7)]
        public string ExternalURL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=8)]
        public bool CanImpersonate;
        
        public AuthenticateGUIDSResponse() {
        }
        
        public AuthenticateGUIDSResponse(int FirstOutParameter, int UserID, string UserName, int ContactID, int DomainID, string DisplayName, string ContactEmail, string ExternalURL, bool CanImpersonate) {
            this.FirstOutParameter = FirstOutParameter;
            this.UserID = UserID;
            this.UserName = UserName;
            this.ContactID = ContactID;
            this.DomainID = DomainID;
            this.DisplayName = DisplayName;
            this.ContactEmail = ContactEmail;
            this.ExternalURL = ExternalURL;
            this.CanImpersonate = CanImpersonate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateContactGUID", WrapperNamespace="http://thinkministry.com/", IsWrapped=true)]
    public partial class AuthenticateContactGUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=0)]
        public string ContactGUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=1)]
        public string DomainGUID;
        
        public AuthenticateContactGUIDRequest() {
        }
        
        public AuthenticateContactGUIDRequest(string ContactGUID, string DomainGUID) {
            this.ContactGUID = ContactGUID;
            this.DomainGUID = DomainGUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateContactGUIDResponse", WrapperNamespace="http://thinkministry.com/", IsWrapped=true)]
    public partial class AuthenticateContactGUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=0)]
        public int FirstOutParameter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=1)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=2)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=3)]
        public int ContactID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=4)]
        public int DomainID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=5)]
        public string DisplayName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=6)]
        public string ContactEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=7)]
        public bool CanImpersonate;
        
        public AuthenticateContactGUIDResponse() {
        }
        
        public AuthenticateContactGUIDResponse(int FirstOutParameter, int UserID, string UserName, int ContactID, int DomainID, string DisplayName, string ContactEmail, bool CanImpersonate) {
            this.FirstOutParameter = FirstOutParameter;
            this.UserID = UserID;
            this.UserName = UserName;
            this.ContactID = ContactID;
            this.DomainID = DomainID;
            this.DisplayName = DisplayName;
            this.ContactEmail = ContactEmail;
            this.CanImpersonate = CanImpersonate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindOrCreateUserAccount", WrapperNamespace="http://thinkministry.com/", IsWrapped=true)]
    public partial class FindOrCreateUserAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=0)]
        public string GUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=2)]
        public string FirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=3)]
        public string LastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=4)]
        public string MobilePhone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=5)]
        public string EmailAddress;
        
        public FindOrCreateUserAccountRequest() {
        }
        
        public FindOrCreateUserAccountRequest(string GUID, string Password, string FirstName, string LastName, string MobilePhone, string EmailAddress) {
            this.GUID = GUID;
            this.Password = Password;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.MobilePhone = MobilePhone;
            this.EmailAddress = EmailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindOrCreateUserAccountResponse", WrapperNamespace="http://thinkministry.com/", IsWrapped=true)]
    public partial class FindOrCreateUserAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=0)]
        public System.Data.DataSet FindOrCreateUserAccountResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=1)]
        public int FirstOutParameter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=2)]
        public int ContactID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=3)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=4)]
        public bool CreatedNewContact;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=5)]
        public bool CreatedNewUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=6)]
        public string NewPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=7)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=8)]
        public string MessageResult;
        
        public FindOrCreateUserAccountResponse() {
        }
        
        public FindOrCreateUserAccountResponse(System.Data.DataSet FindOrCreateUserAccountResult, int FirstOutParameter, int ContactID, int UserID, bool CreatedNewContact, bool CreatedNewUser, string NewPassword, string UserName, string MessageResult) {
            this.FindOrCreateUserAccountResult = FindOrCreateUserAccountResult;
            this.FirstOutParameter = FirstOutParameter;
            this.ContactID = ContactID;
            this.UserID = UserID;
            this.CreatedNewContact = CreatedNewContact;
            this.CreatedNewUser = CreatedNewUser;
            this.NewPassword = NewPassword;
            this.UserName = UserName;
            this.MessageResult = MessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetPassword", WrapperNamespace="http://thinkministry.com/", IsWrapped=true)]
    public partial class ResetPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=0)]
        public string GUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=2)]
        public string FirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=3)]
        public string EmailAddress;
        
        public ResetPasswordRequest() {
        }
        
        public ResetPasswordRequest(string GUID, string Password, string FirstName, string EmailAddress) {
            this.GUID = GUID;
            this.Password = Password;
            this.FirstName = FirstName;
            this.EmailAddress = EmailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetPasswordResponse", WrapperNamespace="http://thinkministry.com/", IsWrapped=true)]
    public partial class ResetPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=0)]
        public string ResetPasswordResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=1)]
        public int UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=2)]
        public string NewPassword;
        
        public ResetPasswordResponse() {
        }
        
        public ResetPasswordResponse(string ResetPasswordResult, int UserID, string NewPassword) {
            this.ResetPasswordResult = ResetPasswordResult;
            this.UserID = UserID;
            this.NewPassword = NewPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AttachFile", WrapperNamespace="http://thinkministry.com/", IsWrapped=true)]
    public partial class AttachFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=0)]
        public string GUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileContents;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=3)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=4)]
        public int PageID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=5)]
        public int RecordID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=6)]
        public string FileDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=7)]
        public bool IsImage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=8)]
        public int ResizeLongestDimension;
        
        public AttachFileRequest() {
        }
        
        public AttachFileRequest(string GUID, string Password, byte[] FileContents, string FileName, int PageID, int RecordID, string FileDescription, bool IsImage, int ResizeLongestDimension) {
            this.GUID = GUID;
            this.Password = Password;
            this.FileContents = FileContents;
            this.FileName = FileName;
            this.PageID = PageID;
            this.RecordID = RecordID;
            this.FileDescription = FileDescription;
            this.IsImage = IsImage;
            this.ResizeLongestDimension = ResizeLongestDimension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AttachFileResponse", WrapperNamespace="http://thinkministry.com/", IsWrapped=true)]
    public partial class AttachFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thinkministry.com/", Order=0)]
        public string AttachFileResult;
        
        public AttachFileResponse() {
        }
        
        public AttachFileResponse(string AttachFileResult) {
            this.AttachFileResult = AttachFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface apiSoapChannel : CheckinSuite.mpapi.apiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class apiSoapClient : System.ServiceModel.ClientBase<CheckinSuite.mpapi.apiSoap>, CheckinSuite.mpapi.apiSoap {
        
        public apiSoapClient() {
        }
        
        public apiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public apiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public apiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public apiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckinSuite.mpapi.AuthenticateUserResponse CheckinSuite.mpapi.apiSoap.AuthenticateUser(CheckinSuite.mpapi.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public int AuthenticateUser(string UserName, string Password, string ServerName, out int UserID, out int ContactID, out int DomainID, out string DomainGUID, out string UserGUID, out string DisplayName, out string ContactEmail, out string ExternalURL, out bool CanImpersonate) {
            CheckinSuite.mpapi.AuthenticateUserRequest inValue = new CheckinSuite.mpapi.AuthenticateUserRequest();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.ServerName = ServerName;
            CheckinSuite.mpapi.AuthenticateUserResponse retVal = ((CheckinSuite.mpapi.apiSoap)(this)).AuthenticateUser(inValue);
            UserID = retVal.UserID;
            ContactID = retVal.ContactID;
            DomainID = retVal.DomainID;
            DomainGUID = retVal.DomainGUID;
            UserGUID = retVal.UserGUID;
            DisplayName = retVal.DisplayName;
            ContactEmail = retVal.ContactEmail;
            ExternalURL = retVal.ExternalURL;
            CanImpersonate = retVal.CanImpersonate;
            return retVal.FirstOutParameter;
        }
        
        public System.Threading.Tasks.Task<CheckinSuite.mpapi.AuthenticateUserResponse> AuthenticateUserAsync(CheckinSuite.mpapi.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckinSuite.mpapi.AuthenticateGUIDSResponse CheckinSuite.mpapi.apiSoap.AuthenticateGUIDS(CheckinSuite.mpapi.AuthenticateGUIDSRequest request) {
            return base.Channel.AuthenticateGUIDS(request);
        }
        
        public int AuthenticateGUIDS(string UserGUID, string DomainGUID, out int UserID, out string UserName, out int ContactID, out int DomainID, out string DisplayName, out string ContactEmail, out string ExternalURL, out bool CanImpersonate) {
            CheckinSuite.mpapi.AuthenticateGUIDSRequest inValue = new CheckinSuite.mpapi.AuthenticateGUIDSRequest();
            inValue.UserGUID = UserGUID;
            inValue.DomainGUID = DomainGUID;
            CheckinSuite.mpapi.AuthenticateGUIDSResponse retVal = ((CheckinSuite.mpapi.apiSoap)(this)).AuthenticateGUIDS(inValue);
            UserID = retVal.UserID;
            UserName = retVal.UserName;
            ContactID = retVal.ContactID;
            DomainID = retVal.DomainID;
            DisplayName = retVal.DisplayName;
            ContactEmail = retVal.ContactEmail;
            ExternalURL = retVal.ExternalURL;
            CanImpersonate = retVal.CanImpersonate;
            return retVal.FirstOutParameter;
        }
        
        public System.Threading.Tasks.Task<CheckinSuite.mpapi.AuthenticateGUIDSResponse> AuthenticateGUIDSAsync(CheckinSuite.mpapi.AuthenticateGUIDSRequest request) {
            return base.Channel.AuthenticateGUIDSAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckinSuite.mpapi.AuthenticateContactGUIDResponse CheckinSuite.mpapi.apiSoap.AuthenticateContactGUID(CheckinSuite.mpapi.AuthenticateContactGUIDRequest request) {
            return base.Channel.AuthenticateContactGUID(request);
        }
        
        public int AuthenticateContactGUID(string ContactGUID, string DomainGUID, out int UserID, out string UserName, out int ContactID, out int DomainID, out string DisplayName, out string ContactEmail, out bool CanImpersonate) {
            CheckinSuite.mpapi.AuthenticateContactGUIDRequest inValue = new CheckinSuite.mpapi.AuthenticateContactGUIDRequest();
            inValue.ContactGUID = ContactGUID;
            inValue.DomainGUID = DomainGUID;
            CheckinSuite.mpapi.AuthenticateContactGUIDResponse retVal = ((CheckinSuite.mpapi.apiSoap)(this)).AuthenticateContactGUID(inValue);
            UserID = retVal.UserID;
            UserName = retVal.UserName;
            ContactID = retVal.ContactID;
            DomainID = retVal.DomainID;
            DisplayName = retVal.DisplayName;
            ContactEmail = retVal.ContactEmail;
            CanImpersonate = retVal.CanImpersonate;
            return retVal.FirstOutParameter;
        }
        
        public System.Threading.Tasks.Task<CheckinSuite.mpapi.AuthenticateContactGUIDResponse> AuthenticateContactGUIDAsync(CheckinSuite.mpapi.AuthenticateContactGUIDRequest request) {
            return base.Channel.AuthenticateContactGUIDAsync(request);
        }
        
        public string GetDomainGUID(string GUID, string Password, string ServerName) {
            return base.Channel.GetDomainGUID(GUID, Password, ServerName);
        }
        
        public System.Threading.Tasks.Task<string> GetDomainGUIDAsync(string GUID, string Password, string ServerName) {
            return base.Channel.GetDomainGUIDAsync(GUID, Password, ServerName);
        }
        
        public System.Data.DataSet GetUserInfo(string GUID, string Password, int UserID) {
            return base.Channel.GetUserInfo(GUID, Password, UserID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUserInfoAsync(string GUID, string Password, int UserID) {
            return base.Channel.GetUserInfoAsync(GUID, Password, UserID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckinSuite.mpapi.FindOrCreateUserAccountResponse CheckinSuite.mpapi.apiSoap.FindOrCreateUserAccount(CheckinSuite.mpapi.FindOrCreateUserAccountRequest request) {
            return base.Channel.FindOrCreateUserAccount(request);
        }
        
        public System.Data.DataSet FindOrCreateUserAccount(string GUID, string Password, string FirstName, string LastName, string MobilePhone, string EmailAddress, out int FirstOutParameter, out int ContactID, out int UserID, out bool CreatedNewContact, out bool CreatedNewUser, out string NewPassword, out string UserName, out string MessageResult) {
            CheckinSuite.mpapi.FindOrCreateUserAccountRequest inValue = new CheckinSuite.mpapi.FindOrCreateUserAccountRequest();
            inValue.GUID = GUID;
            inValue.Password = Password;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.MobilePhone = MobilePhone;
            inValue.EmailAddress = EmailAddress;
            CheckinSuite.mpapi.FindOrCreateUserAccountResponse retVal = ((CheckinSuite.mpapi.apiSoap)(this)).FindOrCreateUserAccount(inValue);
            FirstOutParameter = retVal.FirstOutParameter;
            ContactID = retVal.ContactID;
            UserID = retVal.UserID;
            CreatedNewContact = retVal.CreatedNewContact;
            CreatedNewUser = retVal.CreatedNewUser;
            NewPassword = retVal.NewPassword;
            UserName = retVal.UserName;
            MessageResult = retVal.MessageResult;
            return retVal.FindOrCreateUserAccountResult;
        }
        
        public System.Threading.Tasks.Task<CheckinSuite.mpapi.FindOrCreateUserAccountResponse> FindOrCreateUserAccountAsync(CheckinSuite.mpapi.FindOrCreateUserAccountRequest request) {
            return base.Channel.FindOrCreateUserAccountAsync(request);
        }
        
        public string UpdateUserAccount(string GUID, string Password, int UserID, string FirstName, string LastName, string MobilePhone, string EmailAddress, string NewPassword, string MiddleName, string NickName, int PrefixID, int SuffixID, System.DateTime DOB, int GenderID, int MaritalStatusID) {
            return base.Channel.UpdateUserAccount(GUID, Password, UserID, FirstName, LastName, MobilePhone, EmailAddress, NewPassword, MiddleName, NickName, PrefixID, SuffixID, DOB, GenderID, MaritalStatusID);
        }
        
        public System.Threading.Tasks.Task<string> UpdateUserAccountAsync(string GUID, string Password, int UserID, string FirstName, string LastName, string MobilePhone, string EmailAddress, string NewPassword, string MiddleName, string NickName, int PrefixID, int SuffixID, System.DateTime DOB, int GenderID, int MaritalStatusID) {
            return base.Channel.UpdateUserAccountAsync(GUID, Password, UserID, FirstName, LastName, MobilePhone, EmailAddress, NewPassword, MiddleName, NickName, PrefixID, SuffixID, DOB, GenderID, MaritalStatusID);
        }
        
        public string UpdateUserPassword(string GUID, string Password, int UserID, string NewPassword) {
            return base.Channel.UpdateUserPassword(GUID, Password, UserID, NewPassword);
        }
        
        public System.Threading.Tasks.Task<string> UpdateUserPasswordAsync(string GUID, string Password, int UserID, string NewPassword) {
            return base.Channel.UpdateUserPasswordAsync(GUID, Password, UserID, NewPassword);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckinSuite.mpapi.ResetPasswordResponse CheckinSuite.mpapi.apiSoap.ResetPassword(CheckinSuite.mpapi.ResetPasswordRequest request) {
            return base.Channel.ResetPassword(request);
        }
        
        public string ResetPassword(string GUID, string Password, string FirstName, string EmailAddress, out int UserID, out string NewPassword) {
            CheckinSuite.mpapi.ResetPasswordRequest inValue = new CheckinSuite.mpapi.ResetPasswordRequest();
            inValue.GUID = GUID;
            inValue.Password = Password;
            inValue.FirstName = FirstName;
            inValue.EmailAddress = EmailAddress;
            CheckinSuite.mpapi.ResetPasswordResponse retVal = ((CheckinSuite.mpapi.apiSoap)(this)).ResetPassword(inValue);
            UserID = retVal.UserID;
            NewPassword = retVal.NewPassword;
            return retVal.ResetPasswordResult;
        }
        
        public System.Threading.Tasks.Task<CheckinSuite.mpapi.ResetPasswordResponse> ResetPasswordAsync(CheckinSuite.mpapi.ResetPasswordRequest request) {
            return base.Channel.ResetPasswordAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckinSuite.mpapi.AttachFileResponse CheckinSuite.mpapi.apiSoap.AttachFile(CheckinSuite.mpapi.AttachFileRequest request) {
            return base.Channel.AttachFile(request);
        }
        
        public string AttachFile(string GUID, string Password, byte[] FileContents, string FileName, int PageID, int RecordID, string FileDescription, bool IsImage, int ResizeLongestDimension) {
            CheckinSuite.mpapi.AttachFileRequest inValue = new CheckinSuite.mpapi.AttachFileRequest();
            inValue.GUID = GUID;
            inValue.Password = Password;
            inValue.FileContents = FileContents;
            inValue.FileName = FileName;
            inValue.PageID = PageID;
            inValue.RecordID = RecordID;
            inValue.FileDescription = FileDescription;
            inValue.IsImage = IsImage;
            inValue.ResizeLongestDimension = ResizeLongestDimension;
            CheckinSuite.mpapi.AttachFileResponse retVal = ((CheckinSuite.mpapi.apiSoap)(this)).AttachFile(inValue);
            return retVal.AttachFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CheckinSuite.mpapi.AttachFileResponse> CheckinSuite.mpapi.apiSoap.AttachFileAsync(CheckinSuite.mpapi.AttachFileRequest request) {
            return base.Channel.AttachFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<CheckinSuite.mpapi.AttachFileResponse> AttachFileAsync(string GUID, string Password, byte[] FileContents, string FileName, int PageID, int RecordID, string FileDescription, bool IsImage, int ResizeLongestDimension) {
            CheckinSuite.mpapi.AttachFileRequest inValue = new CheckinSuite.mpapi.AttachFileRequest();
            inValue.GUID = GUID;
            inValue.Password = Password;
            inValue.FileContents = FileContents;
            inValue.FileName = FileName;
            inValue.PageID = PageID;
            inValue.RecordID = RecordID;
            inValue.FileDescription = FileDescription;
            inValue.IsImage = IsImage;
            inValue.ResizeLongestDimension = ResizeLongestDimension;
            return ((CheckinSuite.mpapi.apiSoap)(this)).AttachFileAsync(inValue);
        }
        
        public string UpdateDefaultImage(string GUID, string Password, int PageID, int RecordID, string UniqueName) {
            return base.Channel.UpdateDefaultImage(GUID, Password, PageID, RecordID, UniqueName);
        }
        
        public System.Threading.Tasks.Task<string> UpdateDefaultImageAsync(string GUID, string Password, int PageID, int RecordID, string UniqueName) {
            return base.Channel.UpdateDefaultImageAsync(GUID, Password, PageID, RecordID, UniqueName);
        }
        
        public string AddRecord(string GUID, string Password, int UserID, string TableName, string PrimaryKeyField, string RequestString) {
            return base.Channel.AddRecord(GUID, Password, UserID, TableName, PrimaryKeyField, RequestString);
        }
        
        public System.Threading.Tasks.Task<string> AddRecordAsync(string GUID, string Password, int UserID, string TableName, string PrimaryKeyField, string RequestString) {
            return base.Channel.AddRecordAsync(GUID, Password, UserID, TableName, PrimaryKeyField, RequestString);
        }
        
        public string UpdateRecord(string GUID, string Password, int UserID, string TableName, string PrimaryKeyField, string RequestString) {
            return base.Channel.UpdateRecord(GUID, Password, UserID, TableName, PrimaryKeyField, RequestString);
        }
        
        public System.Threading.Tasks.Task<string> UpdateRecordAsync(string GUID, string Password, int UserID, string TableName, string PrimaryKeyField, string RequestString) {
            return base.Channel.UpdateRecordAsync(GUID, Password, UserID, TableName, PrimaryKeyField, RequestString);
        }
        
        public System.Data.DataSet ExecuteStoredProcedure(string GUID, string Password, string StoredProcedureName, string RequestString) {
            return base.Channel.ExecuteStoredProcedure(GUID, Password, StoredProcedureName, RequestString);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ExecuteStoredProcedureAsync(string GUID, string Password, string StoredProcedureName, string RequestString) {
            return base.Channel.ExecuteStoredProcedureAsync(GUID, Password, StoredProcedureName, RequestString);
        }
        
        public System.Data.DataSet GetRecurringRecords(
                    string GUID, 
                    string Password, 
                    int Pattern, 
                    int Frequency, 
                    System.DateTime StartBy, 
                    System.DateTime EndBy, 
                    int EndAfter, 
                    int SpecificDay, 
                    int OrderDay, 
                    int SpecificMonth, 
                    bool Sunday, 
                    bool Monday, 
                    bool Tuesday, 
                    bool Wednesday, 
                    bool Thursday, 
                    bool Friday, 
                    bool Saturday) {
            return base.Channel.GetRecurringRecords(GUID, Password, Pattern, Frequency, StartBy, EndBy, EndAfter, SpecificDay, OrderDay, SpecificMonth, Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetRecurringRecordsAsync(
                    string GUID, 
                    string Password, 
                    int Pattern, 
                    int Frequency, 
                    System.DateTime StartBy, 
                    System.DateTime EndBy, 
                    int EndAfter, 
                    int SpecificDay, 
                    int OrderDay, 
                    int SpecificMonth, 
                    bool Sunday, 
                    bool Monday, 
                    bool Tuesday, 
                    bool Wednesday, 
                    bool Thursday, 
                    bool Friday, 
                    bool Saturday) {
            return base.Channel.GetRecurringRecordsAsync(GUID, Password, Pattern, Frequency, StartBy, EndBy, EndAfter, SpecificDay, OrderDay, SpecificMonth, Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday);
        }
        
        public System.DateTime GetFirstDateInSeries(
                    string GUID, 
                    string Password, 
                    int Pattern, 
                    int Frequency, 
                    System.DateTime StartBy, 
                    System.DateTime EndBy, 
                    int EndAfter, 
                    int SpecificDay, 
                    int OrderDay, 
                    int SpecificMonth, 
                    bool Sunday, 
                    bool Monday, 
                    bool Tuesday, 
                    bool Wednesday, 
                    bool Thursday, 
                    bool Friday, 
                    bool Saturday) {
            return base.Channel.GetFirstDateInSeries(GUID, Password, Pattern, Frequency, StartBy, EndBy, EndAfter, SpecificDay, OrderDay, SpecificMonth, Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetFirstDateInSeriesAsync(
                    string GUID, 
                    string Password, 
                    int Pattern, 
                    int Frequency, 
                    System.DateTime StartBy, 
                    System.DateTime EndBy, 
                    int EndAfter, 
                    int SpecificDay, 
                    int OrderDay, 
                    int SpecificMonth, 
                    bool Sunday, 
                    bool Monday, 
                    bool Tuesday, 
                    bool Wednesday, 
                    bool Thursday, 
                    bool Friday, 
                    bool Saturday) {
            return base.Channel.GetFirstDateInSeriesAsync(GUID, Password, Pattern, Frequency, StartBy, EndBy, EndAfter, SpecificDay, OrderDay, SpecificMonth, Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday);
        }
        
        public string AddRecurringRecords(
                    string GUID, 
                    string Password, 
                    int UserID, 
                    string TableName, 
                    string PrimaryKeyField, 
                    string RequestString, 
                    string csvSubTabsToCopy, 
                    int CopySubTabsFromRecordID, 
                    int Pattern, 
                    int Frequency, 
                    System.DateTime StartBy, 
                    System.DateTime EndBy, 
                    int EndAfter, 
                    int SpecificDay, 
                    int OrderDay, 
                    int SpecificMonth, 
                    bool Sunday, 
                    bool Monday, 
                    bool Tuesday, 
                    bool Wednesday, 
                    bool Thursday, 
                    bool Friday, 
                    bool Saturday) {
            return base.Channel.AddRecurringRecords(GUID, Password, UserID, TableName, PrimaryKeyField, RequestString, csvSubTabsToCopy, CopySubTabsFromRecordID, Pattern, Frequency, StartBy, EndBy, EndAfter, SpecificDay, OrderDay, SpecificMonth, Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday);
        }
        
        public System.Threading.Tasks.Task<string> AddRecurringRecordsAsync(
                    string GUID, 
                    string Password, 
                    int UserID, 
                    string TableName, 
                    string PrimaryKeyField, 
                    string RequestString, 
                    string csvSubTabsToCopy, 
                    int CopySubTabsFromRecordID, 
                    int Pattern, 
                    int Frequency, 
                    System.DateTime StartBy, 
                    System.DateTime EndBy, 
                    int EndAfter, 
                    int SpecificDay, 
                    int OrderDay, 
                    int SpecificMonth, 
                    bool Sunday, 
                    bool Monday, 
                    bool Tuesday, 
                    bool Wednesday, 
                    bool Thursday, 
                    bool Friday, 
                    bool Saturday) {
            return base.Channel.AddRecurringRecordsAsync(GUID, Password, UserID, TableName, PrimaryKeyField, RequestString, csvSubTabsToCopy, CopySubTabsFromRecordID, Pattern, Frequency, StartBy, EndBy, EndAfter, SpecificDay, OrderDay, SpecificMonth, Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://thinkministry.com/", ConfigurationName="mpapi.FileService")]
    public interface FileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/FileService/GetFile", ReplyAction="http://thinkministry.com/FileService/GetFileResponse")]
        System.IO.Stream GetFile(string dn, string fn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://thinkministry.com/FileService/GetFile", ReplyAction="http://thinkministry.com/FileService/GetFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetFileAsync(string dn, string fn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileServiceChannel : CheckinSuite.mpapi.FileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileServiceClient : System.ServiceModel.ClientBase<CheckinSuite.mpapi.FileService>, CheckinSuite.mpapi.FileService {
        
        public FileServiceClient() {
        }
        
        public FileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream GetFile(string dn, string fn) {
            return base.Channel.GetFile(dn, fn);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetFileAsync(string dn, string fn) {
            return base.Channel.GetFileAsync(dn, fn);
        }
    }
}
